In [2]:

import pandas as pd 

df = pd.read_csv("books.csv", on_bad_lines='skip')
df.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [3]:
# this shows us how many missing values  are hidden in each column
df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [4]:
df.dtypes

bookID                  int64
title                     str
authors                   str
average_rating        float64
isbn                      str
isbn13                  int64
language_code             str
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date          str
publisher                 str
dtype: object

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('books.db')
df.to_sql('books', conn, if_exists='replace', index=False)

print("DataFrame has been written to the SQLite database successfully.")

DataFrame has been written to the SQLite database successfully.

In [10]:
# extract the top 5 books written in english using raw sql query
query = """SELECT title, authors, average_rating, publication_date
           FROM books
           WHERE language_code = 'eng'
           ORDER BY average_rating DESC
           LIMIT 5;
           """
# pull data directly from the SQL server into a fresh variable using pandas read_sql_query method
sql_extracted_df = pd.read_sql_query(query, conn)
sql_extracted_df

,title,authors,average_rating,publication_date
0,Willem de Kooning: Late Paintings,Julie Sylvester/David Sylvester,5.0,9/1/2006
1,Literature Circle Guide: Bridge to Terabithia:...,Tara MacCarthy,5.0,1/1/2002
2,Middlesex Borough (Images of America: New Jersey),Middlesex Borough Heritage Committee,5.0,3/17/2003
3,Zone of the Enders: The 2nd Runner Official St...,Tim Bogenn,5.0,3/6/2003
4,The Diamond Color Meditation: Color Pathway to...,John Diamond,5.0,2/1/2006

In [8]:
# this parses the string data into a standardized DD-MM-YYYY format and stores it in a new column called 'parsed_publication_date'
# error= coerce  turn any completely broken entries  into a safe missing stamp value (NaT) instead of throwing an error

df['parsed_publication_date'] = pd.to_datetime(df['publication_date'], errors='coerce')

# verify the column type changed to datetime64

print("updated Column  Data Type  : ")
print(df['parsed_publication_date'].dtypes)

updated Column  Data Type  :
datetime64[us]